EXEC sp_MSforeachdb N'
	Print ''?''

	if Not ''?'' in (''master'',''model'',''msdb'',''tempdb'')
	Begin
		ALTER database [?] SET RECOVERY SIMPLE;
		USE [?];

		CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;
		CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;
		CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;
		CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;CHECKPOINT;

		Declare @log_File_Name varchar(99)
		Select @log_File_Name = name From sysfiles Where groupid=0;
		Declare @SQLScript VARCHAR(MAX);
		Set @SQLScript = ''ALTER DATABASE [?] MODIFY FILE (NAME = '' + @log_File_Name + '', MAXSIZE = UNLIMITED, FILEGROWTH = 128744KB)'';
	
		Exec(@SQLScript);
		Declare @i int = FILE_IDEX (@log_File_Name);
	
		DBCC SHRINKFILE (@I , 64);	
		DBCC SHRINKFILE (2 , 32);
		DBCC SHRINKDATABASE(N''?'');
	End
	Print ''DD>?'';';
Go 100
